services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: lms-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - dynamodb-data:/data
    networks:
      - lms-net

networks:
  lms-net:
    name: lms-net

volumes:
  dynamodb-data:
